import { z } from "zod";

export const IntentSchema = z.enum([
  "bug",
  "feature_request",
  "how_to",
  "incident",
  "access_request",
  "configuration_change",
  "task",
  "other",
]);

export const AttachmentMetaSchema = z.object({
  filename: z.string(),
  mimeType: z.string().optional(),
  sizeBytes: z.number().optional(),
  url: z.string().optional(),
});

export const EntitySchema = z.object({
  text: z.string(),
  type: z.string().describe("e.g. component, product, person, system, error-code"),
});

/**
 * What we ask Claude to infer. Deliberately excludes facts we already know
 * (ticketKey, summary, description, issueType, priority, attachments, url) -
 * those are merged in afterward from the input, never generated by the model.
 */
export const LlmEnrichmentSchema = z.object({
  category: z.string().describe("Topic/category, e.g. 'authentication', 'billing', 'mobile-ui'"),
  intent: IntentSchema,
  keywords: z.array(z.string()),
  entities: z.array(EntitySchema),
  missingInformation: z.array(z.string()).describe(
    "Information gaps relevant to understanding or resolving the request; empty array if none",
  ),
  retrievalQueries: z
    .array(z.string())
    .describe("2-5 natural-language search queries suitable for a future document/RAG retrieval step"),
});

export type LlmEnrichment = z.infer<typeof LlmEnrichmentSchema>;

/** Final merged shape returned by enhanceRequest(). */
export const EnrichedRequestSchema = LlmEnrichmentSchema.extend({
  ticketKey: z.string(),
  summary: z.string(),
  description: z.string(),
  issueType: z.string().nullable(),
  priority: z.string().nullable(),
  attachments: z.array(AttachmentMetaSchema),
  ticketUrl: z.string(),
});

export type EnrichedRequest = z.infer<typeof EnrichedRequestSchema>;

export type Attachment = z.infer<typeof AttachmentMetaSchema>;
